### ISSUE TITLE
Demo project does not build on Xcode 8.2

### ISSUE THREAD

**Issue by sww314** [SyncDB/AppNetDemo#1]
I am getting a compile error. 
Seems like it should be easy to fix, but I am just trying wrap head around Sync.

Networking.swift:39:13: Ambiguous reference to member 'changes(_:inEntityNamed:predicate:parent:parentRelationship:inContext:operations:completion:)'
![screen shot 2017-02-01 at 6 43 34 pm](https://cloud.githubusercontent.com/assets/1430264/22532694/6a2ece82-e8ae-11e6-92d2-c0eabf429c43.png)

Steps to recreate:
1. git clone https://github.com/SyncDB/AppNetDemo.git
2. cd AppNetDemo/
3. edit Podfile to point at pod 'Sync', '~>2' (the github link failed for me.)
4. pod install
5. open SyncAppNetDemo.xcworkspace/
Get the error trying to build or run.

**Comment by 3lvis** [comment]
@sww314 Hi Scott, should be fixed now. Thanks for reporting this 💐. If you need any help you can also contact me in Gitter. https://gitter.im/SyncDB/Sync
