### ISSUE TITLE
Demo is not working anymore

### ISSUE THREAD

**Issue by achirkof** [SyncDB/AppNetDemo#2]
Hello!
Unfortunately `AppNetURL = "https://api.app.net/posts/stream/global"` not reachable anymore and as a result demo crushes. 
Also demo is out of date because it uses Sync 2.0.

**Comment by 3lvis** [comment]
Damn, any suggestions?

**Comment by 3lvis** [comment]
Maybe this

<img width="404" alt="screen shot 2017-04-17 at 9 25 49 am" src="https://cloud.githubusercontent.com/assets/1088217/25082255/e051d8e4-234f-11e7-8e6f-f4646b724f77.png">

**Comment by achirkof** [comment]
@3lvis yes, I also was going to suggest you this service.

**Comment by 3lvis** [comment]
https://github.com/3lvis/SyncDemo :)
